export const FOODS = {
  proteina: {
    label: "Proteína", emoji: "🥩", color: "#D6F0FF", textColor: "#005A8A",
    items: [
      { id: "huevo", name: "Huevo entero", portion: "1 pieza", kcal: 70, prot: 6, carb: 0, fat: 5 },
      { id: "clara", name: "3 Claras / 90ml", portion: "90ml", kcal: 50, prot: 11, carb: 0, fat: 0 },
      { id: "salmon_fresco", name: "Salmón fresco", portion: "180g", kcal: 320, prot: 36, carb: 0, fat: 18 },
      { id: "salmon_lata", name: "Salmón en lata", portion: "80g", kcal: 120, prot: 18, carb: 0, fat: 5 },
      { id: "salmon_ahumado", name: "Salmón ahumado", portion: "120g", kcal: 160, prot: 22, carb: 0, fat: 8 },
      { id: "atun", name: "Atún en agua", portion: "1 lata ~120g", kcal: 120, prot: 26, carb: 0, fat: 1 },
      { id: "pechuga", name: "Pechuga de pollo", portion: "180g", kcal: 235, prot: 44, carb: 0, fat: 5 },
      { id: "tinga", name: "Tinga de pollo", portion: "180g", kcal: 250, prot: 38, carb: 6, fat: 7 },
      { id: "filete_res", name: "Filete de res", portion: "180g", kcal: 300, prot: 38, carb: 0, fat: 16 },
      { id: "cecina", name: "Cecina", portion: "150g", kcal: 220, prot: 30, carb: 0, fat: 12 },
      { id: "carne_molida", name: "Carne molida 90%", portion: "200g", kcal: 280, prot: 44, carb: 0, fat: 12 },
      { id: "turkey", name: "Turkey patty", portion: "100g", kcal: 160, prot: 22, carb: 0, fat: 8 },
      { id: "jamon_pavo", name: "Jamón de pavo", portion: "60g", kcal: 65, prot: 10, carb: 1, fat: 2 },
      { id: "cottage", name: "Queso cottage", portion: "150g", kcal: 130, prot: 18, carb: 4, fat: 3 },
      { id: "edamames", name: "Edamames", portion: "80g", kcal: 95, prot: 8, carb: 7, fat: 4 },
      { id: "colageno", name: "Colágeno Vital Proteins", portion: "1 scoop ~10g", kcal: 35, prot: 9, carb: 0, fat: 0 },
      { id: "habits", name: "Habits chocolate", portion: "1 scoop ~30g", kcal: 120, prot: 20, carb: 7, fat: 2 },
    ],
  },
  lacteo: {
    label: "Lácteo", emoji: "🥛", color: "#E8F8E8", textColor: "#2A7A2A",
    items: [
      { id: "fage", name: "Yogur Fage 0%", portion: "200g", kcal: 120, prot: 20, carb: 8, fat: 0 },
      { id: "oikos", name: "Yogur Oikos", portion: "150g", kcal: 141, prot: 12, carb: 12, fat: 3 },
      { id: "leche_light", name: "Leche Santa Clara light", portion: "150ml", kcal: 55, prot: 5, carb: 6, fat: 1 },
      { id: "kefir", name: "Kefir shot", portion: "30ml", kcal: 18, prot: 1, carb: 2, fat: 0 },
    ],
  },
  carb: {
    label: "Carb", emoji: "🌽", color: "#FFF0D6", textColor: "#B07000",
    items: [
      { id: "tortilla", name: "Tortilla de maíz", portion: "1 pieza ~30g", kcal: 60, prot: 1, carb: 13, fat: 1 },
      { id: "pan_hogaza", name: "Pan hogaza/integral", portion: "1 rebanada ~35g", kcal: 85, prot: 3, carb: 16, fat: 1 },
      { id: "tostada_melba", name: "Tostada Melba", portion: "3 piezas", kcal: 75, prot: 2, carb: 15, fat: 1 },
      { id: "frijol", name: "Frijoles de olla", portion: "60g", kcal: 80, prot: 5, carb: 14, fat: 0 },
      { id: "avena", name: "Avena en hojuela", portion: "40g", kcal: 150, prot: 5, carb: 27, fat: 3 },
      { id: "arroz", name: "Arroz blanco cocido", portion: "100g", kcal: 130, prot: 3, carb: 28, fat: 0 },
      { id: "quinoa", name: "Quinoa cocida", portion: "100g", kcal: 120, prot: 4, carb: 22, fat: 2 },
      { id: "papa", name: "Papa horneada en gajos", portion: "200g", kcal: 160, prot: 4, carb: 36, fat: 1 },
      { id: "pasta_normal", name: "Pasta normal cocida", portion: "150g", kcal: 220, prot: 8, carb: 43, fat: 1 },
      { id: "pasta_proteina", name: "Pasta proteína Chedraui", portion: "85g seca", kcal: 310, prot: 25, carb: 40, fat: 3 },
    ],
  },
  grasa: {
    label: "Grasa", emoji: "🥑", color: "#FFE8E8", textColor: "#A03030",
    items: [
      { id: "aguacate", name: "Aguacate", portion: "60g ~1/4", kcal: 95, prot: 1, carb: 5, fat: 9 },
      { id: "aceite", name: "Aceite de oliva", portion: "10ml", kcal: 88, prot: 0, carb: 0, fat: 10 },
      { id: "kerrygold", name: "Mantequilla Kerrygold", portion: "10g", kcal: 74, prot: 0, carb: 0, fat: 8 },
      { id: "ghee", name: "Ghee", portion: "10g", kcal: 90, prot: 0, carb: 0, fat: 10 },
      { id: "salsa_macha", name: "Salsa macha", portion: "10g", kcal: 45, prot: 0, carb: 1, fat: 4 },
      { id: "peanut", name: "Peanut butter", portion: "16g", kcal: 95, prot: 4, carb: 3, fat: 8 },
      { id: "manchego", name: "Queso manchego", portion: "30g", kcal: 108, prot: 7, carb: 0, fat: 9 },
      { id: "chocolate_lindt85", name: "Lindt 85%", portion: "18g", kcal: 105, prot: 2, carb: 4, fat: 9 },
      { id: "chocolate_lindt80", name: "Lindt 80%", portion: "18g", kcal: 108, prot: 2, carb: 6, fat: 9 },
      { id: "datil", name: "Dátil", portion: "1 pieza ~8g", kcal: 23, prot: 0, carb: 6, fat: 0 },
    ],
  },
  fruta: {
    label: "Fruta", emoji: "🍎", color: "#F8E8FF", textColor: "#7A2A7A",
    items: [
      { id: "berries", name: "Berries mixtos", portion: "120g", kcal: 50, prot: 1, carb: 12, fat: 0 },
      { id: "manzana", name: "Manzana verde", portion: "1 pieza", kcal: 78, prot: 0, carb: 21, fat: 0 },
      { id: "melon", name: "Melón", portion: "120g", kcal: 43, prot: 1, carb: 11, fat: 0 },
      { id: "jicama", name: "Jícama", portion: "100g", kcal: 40, prot: 1, carb: 9, fat: 0 },
      { id: "platano", name: "Plátano pequeño", portion: "80g", kcal: 72, prot: 1, carb: 19, fat: 0 },
    ],
  },
  verdura: {
    label: "Verdura libre", emoji: "🥦", color: "#E8FFE8", textColor: "#1A6A1A",
    items: [
      { id: "nopales", name: "Nopales", portion: "150g", kcal: 30, prot: 2, carb: 5, fat: 0 },
      { id: "broccolini", name: "Broccolini", portion: "120g", kcal: 35, prot: 3, carb: 6, fat: 0 },
      { id: "pepino", name: "Pepino", portion: "100g", kcal: 15, prot: 1, carb: 3, fat: 0 },
      { id: "tomate", name: "Tomate / cherry", portion: "100g", kcal: 18, prot: 1, carb: 4, fat: 0 },
      { id: "cebolla", name: "Cebolla morada", portion: "50g", kcal: 20, prot: 1, carb: 5, fat: 0 },
    ],
  },
  alcohol: {
    label: "Alcohol", emoji: "🍹", color: "#FFF0F8", textColor: "#8A0050",
    items: [
      { id: "victoria", name: "Victoria / Modelo", portion: "355ml", kcal: 150, prot: 1, carb: 13, fat: 0 },
      { id: "michelob", name: "Michelob Ultra", portion: "355ml", kcal: 95, prot: 1, carb: 3, fat: 0 },
      { id: "mezcal", name: "Mezcal shot", portion: "45ml", kcal: 105, prot: 0, carb: 0, fat: 0 },
      { id: "tequila_mineral", name: "Tequila con agua mineral", portion: "45ml tequila", kcal: 105, prot: 0, carb: 0, fat: 0 },
      { id: "carajillo", name: "Carajillo", portion: "45ml Licor 43", kcal: 155, prot: 0, carb: 17, fat: 0 },
      { id: "vino_blanco", name: "Vino blanco copa", portion: "150ml", kcal: 120, prot: 0, carb: 4, fat: 0 },
      { id: "cuba", name: "Cuba Bacardi + Coca Zero", portion: "45ml Bacardi", kcal: 100, prot: 0, carb: 0, fat: 0 },
    ],
  },
  antojo: {
    label: "Antojos", emoji: "🍫", color: "#F5F5F5", textColor: "#555",
    items: [
      { id: "emperador", name: "Galletas Emperador paquete", portion: "55g", kcal: 430, prot: 4, carb: 62, fat: 18 },
      { id: "takis", name: "Takis Fuego bolsa chica", portion: "42g", kcal: 210, prot: 3, carb: 27, fat: 10 },
      { id: "taco_bistec", name: "Taco bistec de la calle", portion: "1 taco ~100g", kcal: 195, prot: 14, carb: 18, fat: 7 },
      { id: "taco_pastor", name: "Taco al pastor de la calle", portion: "1 taco ~90g", kcal: 180, prot: 12, carb: 18, fat: 6 },
      { id: "sushi_rollo", name: "Rollo sushi 8 pzas", portion: "180g", kcal: 280, prot: 10, carb: 44, fat: 6 },
      { id: "yakimeshi", name: "Yakimeshi porción", portion: "250g", kcal: 380, prot: 12, carb: 52, fat: 14 },
      { id: "kinder", name: "Kinder Bueno barra", portion: "43g", kcal: 230, prot: 4, carb: 25, fat: 13 },
      { id: "nutella", name: "Nutella 1 cda", portion: "20g", kcal: 110, prot: 1, carb: 12, fat: 6 },
      { id: "carlos_quinto", name: "Carlos Quinto mini s/azúcar", portion: "17g", kcal: 75, prot: 1, carb: 8, fat: 4 },
      { id: "cajeta", name: "Cajeta 1 cda", portion: "20g", kcal: 65, prot: 0, carb: 16, fat: 1 },
      { id: "oreo_tapas", name: "Oreo 2 tapas sin relleno", portion: "10g", kcal: 48, prot: 1, carb: 8, fat: 2 },
      { id: "pasta_alfredo", name: "Pasta Alfredo porción", portion: "300g", kcal: 650, prot: 18, carb: 72, fat: 32 },
    ],
  },
};
