export const FOODS = {
  proteina: {
    label: "Proteína", emoji: "🥩", color: "#D6F0FF", textColor: "#005A8A",
    items: [
      { id: "huevo", name: "Huevo entero", portion: "1 pieza", kcal: 70, prot: 6, carb: 0, fat: 5, sugar: 0, flag: "green", gluten: false },
      { id: "clara", name: "3 Claras / 90ml", portion: "90ml", kcal: 50, prot: 11, carb: 0, fat: 0, sugar: 0, flag: "green", gluten: false },
      { id: "salmon_fresco", name: "Salmón filete", portion: "180g", kcal: 320, prot: 36, carb: 0, fat: 18, sugar: 0, flag: "green", gluten: false },
      { id: "salmon_ahumado", name: "Salmón ahumado", portion: "120g", kcal: 160, prot: 22, carb: 0, fat: 8, sugar: 0, flag: "yellow", gluten: false },
      { id: "atun_lata", name: "Atún en lata", portion: "1 lata ~120g", kcal: 120, prot: 26, carb: 0, fat: 1, sugar: 0, flag: "yellow", gluten: false },
      { id: "atun_filete", name: "Atún filete", portion: "180g", kcal: 240, prot: 42, carb: 0, fat: 7, sugar: 0, flag: "green", gluten: false },
      { id: "pechuga", name: "Pechuga de pollo", portion: "180g", kcal: 235, prot: 44, carb: 0, fat: 5, sugar: 0, flag: "green", gluten: false },
      { id: "pollo_deshebrado", name: "Pollo deshebrado", portion: "180g", kcal: 220, prot: 40, carb: 0, fat: 5, sugar: 0, flag: "green", gluten: false },
      { id: "tinga", name: "Tinga de pollo", portion: "180g", kcal: 250, prot: 38, carb: 6, fat: 7, sugar: 2, flag: "yellow", gluten: false },
      { id: "filete_res", name: "Filete de res", portion: "180g", kcal: 300, prot: 38, carb: 0, fat: 16, sugar: 0, flag: "green", gluten: false },
      { id: "cecina", name: "Cecina", portion: "150g", kcal: 220, prot: 30, carb: 0, fat: 12, sugar: 0, flag: "yellow", gluten: false },
      { id: "carne_molida", name: "Carne molida 90%", portion: "200g", kcal: 280, prot: 44, carb: 0, fat: 12, sugar: 0, flag: "green", gluten: false },
      { id: "turkey", name: "Turkey patty", portion: "100g", kcal: 160, prot: 22, carb: 0, fat: 8, sugar: 0, flag: "yellow", gluten: false },
      { id: "jamon_pavo", name: "Jamón de pavo", portion: "60g", kcal: 65, prot: 10, carb: 1, fat: 2, sugar: 0, flag: "red", gluten: false },
      { id: "cottage", name: "Queso cottage", portion: "150g", kcal: 130, prot: 18, carb: 4, fat: 3, sugar: 3, flag: "green", gluten: false },
      { id: "edamames", name: "Edamames", portion: "80g", kcal: 95, prot: 8, carb: 7, fat: 4, sugar: 1, flag: "green", gluten: false },
      { id: "colageno", name: "Colágeno Vital Proteins", portion: "1 scoop ~10g", kcal: 35, prot: 9, carb: 0, fat: 0, sugar: 0, flag: "green", gluten: false },
      { id: "habits", name: "Habits chocolate", portion: "1 scoop ~30g", kcal: 120, prot: 20, carb: 7, fat: 2, sugar: 3, flag: "yellow", gluten: false },
    ],
  },
  lacteo: {
    label: "Lácteo", emoji: "🥛", color: "#E8F8E8", textColor: "#2A7A2A",
    items: [
      { id: "fage", name: "Yogur Fage 0%", portion: "200g", kcal: 120, prot: 20, carb: 8, fat: 0, sugar: 8, flag: "green", gluten: false },
      { id: "oikos", name: "Yogur Oikos", portion: "150g", kcal: 141, prot: 12, carb: 12, fat: 3, sugar: 6, flag: "yellow", gluten: false },
      { id: "leche_light", name: "Leche Santa Clara light", portion: "150ml", kcal: 55, prot: 5, carb: 6, fat: 1, sugar: 6, flag: "yellow", gluten: false },
      { id: "kefir", name: "Kefir shot", portion: "30ml", kcal: 18, prot: 1, carb: 2, fat: 0, sugar: 2, flag: "green", gluten: false },
    ],
  },
  carb: {
    label: "Carb", emoji: "🌽", color: "#FFF0D6", textColor: "#B07000",
    items: [
      { id: "tortilla_nopal", name: "Tortilla de nopal (Señor Cactus)", portion: "1 pieza ~30g", kcal: 30, prot: 1, carb: 5, fat: 0, sugar: 0, flag: "green", gluten: false },
      { id: "tortilla", name: "Tortilla de maíz", portion: "1 pieza ~30g", kcal: 64, prot: 1, carb: 13, fat: 1, sugar: 0, flag: "green", gluten: false },
      { id: "tortilla_harina", name: "Tortillina Tía Rosa", portion: "1 pieza ~25g", kcal: 76, prot: 2, carb: 13, fat: 3, sugar: 0, flag: "red", gluten: true },
      { id: "pan_hogaza", name: "Pan hogaza/integral", portion: "1 rebanada ~35g", kcal: 85, prot: 3, carb: 16, fat: 1, sugar: 1, flag: "yellow", gluten: true },
      { id: "pan_cero_cero", name: "Pan Cero Cero Bimbo", portion: "1 rebanada ~27g", kcal: 69, prot: 3, carb: 13, fat: 0, sugar: 0, flag: "red", gluten: true },
      { id: "tostada_melba", name: "Tostada Melba", portion: "3 piezas", kcal: 75, prot: 2, carb: 15, fat: 1, sugar: 0, flag: "yellow", gluten: true },
      { id: "frijol_sierra", name: "Frijol La Sierra bayo refrito", portion: "media taza ~120g", kcal: 110, prot: 5, carb: 12, fat: 5, sugar: 0, flag: "yellow", gluten: false },
      { id: "frijol_bayo_bolsa", name: "Frijol bayo refrito de bolsa", portion: "media taza ~130g", kcal: 99, prot: 4, carb: 9, fat: 5, sugar: 0, flag: "yellow", gluten: false },
      { id: "avena", name: "Avena en hojuela", portion: "40g", kcal: 150, prot: 5, carb: 27, fat: 3, sugar: 1, flag: "green", gluten: false },
      { id: "arroz", name: "Arroz blanco cocido", portion: "100g", kcal: 130, prot: 3, carb: 28, fat: 0, sugar: 0, flag: "yellow", gluten: false },
      { id: "quinoa", name: "Quinoa cocida", portion: "media taza ~90g", kcal: 110, prot: 4, carb: 20, fat: 2, sugar: 0, flag: "green", gluten: false },
      { id: "papa", name: "Papa horneada en gajos", portion: "200g", kcal: 160, prot: 4, carb: 36, fat: 1, sugar: 1, flag: "green", gluten: false },
      { id: "pasta_normal", name: "Pasta normal cocida", portion: "150g", kcal: 220, prot: 8, carb: 43, fat: 1, sugar: 1, flag: "red", gluten: true },
      { id: "pasta_proteina", name: "Pasta proteína Chedraui", portion: "85g seca", kcal: 310, prot: 25, carb: 40, fat: 3, sugar: 2, flag: "yellow", gluten: true },
    ],
  },
  grasa: {
    label: "Grasa", emoji: "🥑", color: "#FFE8E8", textColor: "#A03030",
    items: [
      { id: "aguacate", name: "Aguacate", portion: "60g ~1/4", kcal: 95, prot: 1, carb: 5, fat: 9, sugar: 0, flag: "green", gluten: false },
      { id: "aceite", name: "Aceite de oliva", portion: "10ml", kcal: 88, prot: 0, carb: 0, fat: 10, sugar: 0, flag: "green", gluten: false },
      { id: "kerrygold", name: "Mantequilla Kerrygold", portion: "10g", kcal: 74, prot: 0, carb: 0, fat: 8, sugar: 0, flag: "green", gluten: false },
      { id: "ghee", name: "Ghee", portion: "10g", kcal: 90, prot: 0, carb: 0, fat: 10, sugar: 0, flag: "green", gluten: false },
      { id: "media_crema", name: "Media crema 1 cda", portion: "15g", kcal: 50, prot: 0, carb: 1, fat: 5, sugar: 1, flag: "yellow", gluten: false },
      { id: "crema_alpura", name: "Crema Alpura 1 cda", portion: "15g", kcal: 35, prot: 0, carb: 1, fat: 3, sugar: 1, flag: "yellow", gluten: false },
      { id: "salsa_macha", name: "Salsa macha", portion: "10g", kcal: 45, prot: 0, carb: 1, fat: 4, sugar: 0, flag: "green", gluten: false },
      { id: "peanut", name: "Peanut butter", portion: "16g", kcal: 95, prot: 4, carb: 3, fat: 8, sugar: 1, flag: "yellow", gluten: false },
      { id: "manchego", name: "Queso manchego", portion: "30g", kcal: 108, prot: 7, carb: 0, fat: 9, sugar: 0, flag: "yellow", gluten: false },
      { id: "chocolate_lindt85", name: "Lindt 85%", portion: "18g", kcal: 105, prot: 2, carb: 4, fat: 9, sugar: 2, flag: "green", gluten: false },
      { id: "chocolate_lindt80", name: "Lindt 80%", portion: "18g", kcal: 108, prot: 2, carb: 6, fat: 9, sugar: 3, flag: "green", gluten: false },
      { id: "datil", name: "Dátil solo", portion: "1 pieza ~8g", kcal: 23, prot: 0, carb: 6, fat: 0, sugar: 5, flag: "yellow", gluten: false },
      { id: "datil_chocolate", name: "Dátil con Lindt 80% derretido", portion: "1 pieza con ~5g choco", kcal: 58, prot: 0, carb: 10, fat: 2, sugar: 7, flag: "yellow", gluten: false },
    ],
  },
  fruta: {
    label: "Fruta", emoji: "🍎", color: "#F8E8FF", textColor: "#7A2A7A",
    items: [
      { id: "berries", name: "Berries mixtos", portion: "120g", kcal: 50, prot: 1, carb: 12, fat: 0, sugar: 8, flag: "green", gluten: false },
      { id: "manzana", name: "Manzana verde", portion: "1 pieza", kcal: 78, prot: 0, carb: 21, fat: 0, sugar: 16, flag: "green", gluten: false },
      { id: "melon", name: "Melón", portion: "120g", kcal: 43, prot: 1, carb: 11, fat: 0, sugar: 10, flag: "green", gluten: false },
      { id: "jicama", name: "Jícama", portion: "100g", kcal: 40, prot: 1, carb: 9, fat: 0, sugar: 2, flag: "green", gluten: false },
      { id: "platano", name: "Plátano pequeño", portion: "80g", kcal: 72, prot: 1, carb: 19, fat: 0, sugar: 10, flag: "green", gluten: false },
      { id: "uvas_verdes", name: "Uvas verdes", portion: "100g (~20 uvas)", kcal: 55, prot: 1, carb: 15, fat: 0, sugar: 15, flag: "green", gluten: false },
    ],
  },
  verdura: {
    label: "Verdura libre", emoji: "🥦", color: "#E8FFE8", textColor: "#1A6A1A",
    items: [
      { id: "nopales", name: "Nopales", portion: "150g", kcal: 30, prot: 2, carb: 5, fat: 0, sugar: 0, flag: "green", gluten: false },
      { id: "broccolini", name: "Broccolini", portion: "120g", kcal: 35, prot: 3, carb: 6, fat: 0, sugar: 1, flag: "green", gluten: false },
      { id: "pepino", name: "Pepino", portion: "100g", kcal: 15, prot: 1, carb: 3, fat: 0, sugar: 1, flag: "green", gluten: false },
      { id: "tomate", name: "Tomate / cherry", portion: "100g", kcal: 18, prot: 1, carb: 4, fat: 0, sugar: 3, flag: "green", gluten: false },
      { id: "cebolla", name: "Cebolla morada", portion: "50g", kcal: 20, prot: 1, carb: 5, fat: 0, sugar: 2, flag: "green", gluten: false },
    ],
  },
  alcohol: {
    label: "Alcohol", emoji: "🍹", color: "#FFF0F8", textColor: "#8A0050",
    items: [
      { id: "victoria", name: "Victoria / Modelo", portion: "355ml", kcal: 150, prot: 1, carb: 13, fat: 0, sugar: 0, flag: "red", gluten: true },
      { id: "michelob", name: "Michelob Ultra", portion: "355ml", kcal: 95, prot: 1, carb: 3, fat: 0, sugar: 0, flag: "yellow", gluten: true },
      { id: "mezcal", name: "Mezcal shot", portion: "45ml", kcal: 105, prot: 0, carb: 0, fat: 0, sugar: 0, flag: "yellow", gluten: false },
      { id: "tequila_mineral", name: "Tequila con agua mineral", portion: "45ml tequila", kcal: 105, prot: 0, carb: 0, fat: 0, sugar: 0, flag: "yellow", gluten: false },
      { id: "carajillo", name: "Carajillo", portion: "45ml Licor 43", kcal: 155, prot: 0, carb: 17, fat: 0, sugar: 15, flag: "red", gluten: false },
      { id: "vino_blanco", name: "Vino blanco copa", portion: "150ml", kcal: 120, prot: 0, carb: 4, fat: 0, sugar: 1, flag: "yellow", gluten: false },
      { id: "cuba", name: "Cuba Bacardi + Coca Zero", portion: "45ml Bacardi", kcal: 100, prot: 0, carb: 0, fat: 0, sugar: 0, flag: "yellow", gluten: false },
    ],
  },
  recetas: {
    label: "Recetas caseras", emoji: "🍲", color: "#E8F4FF", textColor: "#00508A",
    items: [
      { id: "sopa_nopal", name: "Sopa de nopal (1 plato)", portion: "300ml aprox", kcal: 120, prot: 6, carb: 14, fat: 3, sugar: 1, flag: "green", gluten: false },
      { id: "sopa_calabacin", name: "Sopa de calabacín (1 plato)", portion: "300ml aprox", kcal: 90, prot: 4, carb: 10, fat: 3, sugar: 4, flag: "green", gluten: false },
      { id: "tasajo", name: "Tasajo asado", portion: "250g", kcal: 380, prot: 48, carb: 0, fat: 20, sugar: 0, flag: "yellow", gluten: false },
      { id: "aguachile_cecina", name: "Aguachile de cecina (sin aguacate)", portion: "1 porción ~150g", kcal: 280, prot: 30, carb: 12, fat: 12, sugar: 2, flag: "green", gluten: false },
      { id: "agua_mango", name: "Agua de mango natural", portion: "250ml", kcal: 95, prot: 1, carb: 24, fat: 0, sugar: 22, flag: "yellow", gluten: false },
    ],
  },
  antojo: {
    label: "Antojos", emoji: "🍫", color: "#F5F5F5", textColor: "#555",
    items: [
      { id: "emperador", name: "Galletas Emperador paquete", portion: "55g", kcal: 430, prot: 4, carb: 62, fat: 18, sugar: 32, flag: "red", gluten: true },
      { id: "takis", name: "Takis Fuego bolsa chica", portion: "42g", kcal: 210, prot: 3, carb: 27, fat: 10, sugar: 2, flag: "red", gluten: true },
      { id: "taco_bistec", name: "Taco bistec de la calle", portion: "1 taco ~100g", kcal: 195, prot: 14, carb: 18, fat: 7, sugar: 0, flag: "yellow", gluten: false },
      { id: "taco_pastor", name: "Taco al pastor de la calle", portion: "1 taco ~90g", kcal: 180, prot: 12, carb: 18, fat: 6, sugar: 1, flag: "yellow", gluten: false },
      { id: "sushi_rollo", name: "Rollo sushi 8 pzas", portion: "180g", kcal: 280, prot: 10, carb: 44, fat: 6, sugar: 4, flag: "yellow", gluten: true },
      { id: "yakimeshi", name: "Yakimeshi porción", portion: "250g", kcal: 380, prot: 12, carb: 52, fat: 14, sugar: 3, flag: "yellow", gluten: true },
      { id: "kinder", name: "Kinder Bueno barra", portion: "43g", kcal: 230, prot: 4, carb: 25, fat: 13, sugar: 20, flag: "red", gluten: true },
      { id: "nutella", name: "Nutella 1 cda sopera", portion: "20g", kcal: 110, prot: 1, carb: 12, fat: 6, sugar: 11, flag: "red", gluten: true },
      { id: "carlos_quinto", name: "Carlos Quinto mini s/azúcar", portion: "17g", kcal: 75, prot: 1, carb: 8, fat: 4, sugar: 1, flag: "yellow", gluten: false },
      { id: "cajeta", name: "Cajeta 1 cda sopera", portion: "20g", kcal: 65, prot: 0, carb: 16, fat: 1, sugar: 14, flag: "red", gluten: false },
      { id: "oreo_tapas", name: "Oreo 2 tapas sin relleno", portion: "10g", kcal: 48, prot: 1, carb: 8, fat: 2, sugar: 4, flag: "red", gluten: true },
      { id: "pasta_alfredo", name: "Pasta Alfredo porción", portion: "300g", kcal: 650, prot: 18, carb: 72, fat: 32, sugar: 4, flag: "red", gluten: true },
      { id: "panque_chocolate", name: "Panqué de chocolate rebanada", portion: "1 rebanada ~80g", kcal: 325, prot: 4, carb: 42, fat: 16, sugar: 28, flag: "red", gluten: true },
      { id: "pizza_mariscos", name: "Pizza Toscana mariscos c/tocino", portion: "1 rebanada ~120g", kcal: 350, prot: 15, carb: 32, fat: 16, sugar: 2, flag: "yellow", gluten: true },
      { id: "polvorones", name: "Polvorones Marinela (4 galletas)", portion: "4 piezas ~56g", kcal: 290, prot: 2, carb: 36, fat: 16, sugar: 18, flag: "red", gluten: true },
      { id: "tostada_atun", name: "Tostada de atún (Milpa Real)", portion: "1 tostada completa", kcal: 360, prot: 18, carb: 22, fat: 18, sugar: 1, flag: "yellow", gluten: false },
    ],
  },
};
